### ISSUE TITLE
Where cogwork fears to tread

### ISSUE THREAD

**Issue by RojjaCebolla** [dsoskey/cogwork-librarian#10]
Managed to get this error:
![image](https://github.com/dsoskey/cogwork-librarian/assets/62170514/e1415d8e-5d71-4d94-a157-1fb3152323dc)

The search i used was the following:
```
@defaultWeight:uniform

(fo:/\btoken/ or o:/put a.*counter/ or o:proliferate or o:populate) order:edhrec prefer:usd-low -frame:showcase
fo:/\btoken/
o:/put a.*counter/
o:proliferate
o:populate
whenever or -is:permanent or o:/enters?\b/
-is:extra
ci<2
-t:instant -kw:flash
```
![image](https://github.com/dsoskey/cogwork-librarian/assets/62170514/a8a59412-a1c1-4592-a234-6dbf750dcb77)

**Comment by RojjaCebolla** [comment]
is there a non-breaking line break that i can use? Like
(fo:/\btoken/ or o:/put a.*counter/ or o:proliferate or o:populate) order:edhrec \\
prefer:usd-low -frame:showcase

and have all of that count as the first line, not as BASE and SUB1

**Comment by dsoskey** [comment]
what URL does your browser show when you see that message? I get a different error message when running the same query set. 

As for multi-line breaks, there is not support for that but i like the idea. I've created a separate issue to track that feature

**Comment by RojjaCebolla** [comment]
i think i didn't have a database!

**Comment by RojjaCebolla** [comment]
cuz that date>LRW thing had never started working for me, even though i refreshed the page

**Comment by RojjaCebolla** [comment]
so i eventually found a setting where i could redownload tags and art and a database, and like, i think a spot that has some text now, didn't have any text earlier today.

might be due to cookie autodelete, but that's whitelisted
![image](https://github.com/dsoskey/cogwork-librarian/assets/62170514/43a53ce0-8f54-499c-a064-3947852bc230)
