### ISSUE TITLE
project-wide filters

### ISSUE THREAD

**Issue by RojjaCebolla** [dsoskey/cogwork-librarian#13]
![image](https://github.com/dsoskey/cogwork-librarian/assets/62170514/a67f27e5-1435-4075-9ec9-886c3c094efd)
any filters that are on the first line of your project, would apply to your whole project
maybe to denote them specially (so that people don't use them by accident?), such a project filter would start with a `@directive` like maybe @defaultFilter ?

**Comment by dsoskey** [comment]
V1 of this is live now. Ill keep this open to track adding docs for the feature. Put `@defaultDomain(QUERY)` in its own paragraph to prefix all queries in a project with QUERY.

**Comment by dsoskey** [comment]
Docs have shipped
