### ISSUE TITLE
View Scryfall tags associated with a card/list of cards

### ISSUE THREAD

**Issue by dsoskey** [dsoskey/cogwork-librarian#15]
**Is your feature request related to a problem? Please describe.**
I don't necessarily know which tags i want to look at for a given card in my cube, so I can't use the filter to see the information i want.

**Describe the solution you'd like**
As a cube owner I want to be able to see which scryfall tags are associated with cards in my cube list.

**Additional context**
Suggested by Discord user internet on the MTG Cube Talk server

**Comment by RojjaCebolla** [comment]
![image](https://github.com/user-attachments/assets/80177ff3-0b51-407d-913a-9692edb14193)
i find charts hard to read at times, but i love tables!

**Comment by dsoskey** [comment]
this but for a list of search queries

**Comment by dsoskey** [comment]
this but for a list of search queries is coming soon

**Comment by dsoskey** [comment]
Its out! try it at https://coglib.sosk.watch/cube/soskgy/table?source=cubecobra
