### ISSUE TITLE
Out-of-date sets are included in f:standard

### ISSUE THREAD

**Issue by RojjaCebolla** [dsoskey/cogwork-librarian#16]
![image](https://github.com/user-attachments/assets/30969a6f-cbd9-419a-94eb-5d94fee4a9d2)
it should only be including >=WOE

**Comment by dsoskey** [comment]
when did you last update your card data set? Format legality is encoded directly on the scryfall bulk data so it won't change on its own

**Comment by RojjaCebolla** [comment]
ohhhh, i assumed it auto updates, i'll redownload! thanks!

**Comment by dsoskey** [comment]
A full db refresh is pretty intensive so i've left it to be manually refreshed for now

**Comment by RojjaCebolla** [comment]
all good now, thank you!
