### ISSUE TITLE
Keyboard shortcut for submitting a query

### ISSUE THREAD

**Issue by hzeis** [dsoskey/cogwork-librarian#5]
It would be nice to have some way to submit a query from the query editor. Maybe I missed it, but I've been clicking on "scour the library" a lot and I'd like to not do that. Maybe Shift+Enter goes to the next line in the editor and Enter submits? Ctrl+Enter would also work well if you want to keep multi-line editing nice.

**Comment by dsoskey** [comment]
Its not documented anywhere, but when you're focused on the editor, Meta Key + Enter submits a query while maintaining focus on the editor. Looking at mdn, it seems like not every OS supports tracking the Meta Key. I'll add Ctrl + Enter as an alternative keystroke.

**Comment by dsoskey** [comment]
Ctrl+Enter shortcut has shipped. https://github.com/dsoskey/cogwork-librarian/commit/15e48f1e86530ed98dc6546db13b738fc43fd842

I'll keep this open to track adding keyboard shortcut documentation

**Comment by hzeis** [comment]
I think the "About Me" section is currently the place I'd expect to find that.

**Comment by dsoskey** [comment]
this information is now located in the (under construction) user guide: https://coglib.sosk.watch/user-guide/keyboard-shortcuts
