### ISSUE TITLE
Jump to first card after submitting a query

### ISSUE THREAD

**Issue by hzeis** [dsoskey/cogwork-librarian#6]
If you're multiple pages into a search and then submit another query the page index/scroll position stays the same. This can often result in staying on an empty page because the new query matches fewer cards. It would be nice to jump to the very start of the new search when a query is submitted.

**Comment by dsoskey** [comment]
the fix has been pushed to main. feel free to reopen if you run into any issues with the page resetting

https://github.com/dsoskey/cogwork-librarian/commit/15e48f1e86530ed98dc6546db13b738fc43fd842
