### ISSUE TITLE
Remove ignored cards

### ISSUE THREAD

**Issue by soph-harris-31** [dsoskey/cogwork-librarian#7]
I sometimes go through ignoring cards quickly and accidentally ignore cards I don't want to, it would be great to have a way to un-ignore cards?

**Comment by dsoskey** [comment]
I've got some plans for improving the saved/ignored card lists through a project workflow. when looking at your ignored cards would you want to see all of them at once?

**Comment by Simonharris3** [comment]
I think so, not sure what the alternative would be.

**Comment by dsoskey** [comment]
At the moment I have a view under feature flags that let you see cards that were ignored in the current search, but that'd require you to search for specific cards. I considered an is:ignored filter to look at all of the ignored cards, but I could also make dedicated view separate from the search context

**Comment by soph-harris-31** [comment]
Ah I see, that would probably be fine, though ideally it'd be nice to see all of the ignored cards

**Comment by dsoskey** [comment]
I've shipped a change that lets you see the ignored cards in a search and unIgnore them. To see all your ignored cards use the identity filter `*` to search for everything.
