### ISSUE TITLE
Weird behavior when typing in and deleting saved cards

### ISSUE THREAD

**Issue by soph-harris-31** [dsoskey/cogwork-librarian#8]
Cards disappear and re-appear from my saved cards list when I do one of the following:

1. Type a card into the saved cards list
2. Switch to another tab or window without pressing enter or clicking elsewhere on the page.
3. Switch back to the window or tab with cogwork librarian. The card will now not appear on the saved cards list.
4. Click on any part of the page outside of the saved cards list. The card will now appear on the saved cards list.
5. Click on the card in the saved cards list. The card will now not appear.

I can repeat steps 4 and 5 with the same behavior.

1. Type a card into the saved cards list.
2. Delete some or all of the text from that card's name.
3. Click on any part of the page outside of the saved cards list. The card's full name will now appear on the saved cards list.
4. Click on the card in the saved cards list. The card will now not appear.

Similar to the first method, I can repeat steps 3 and 4 with the same behavior. Notably, if I instead click on another card in the saved cards list rather than elsewhere on the page, the bug no longer occurs and the text I have typed or deleted will be saved.

Windows, Firefox 123.0.1

**Comment by dsoskey** [comment]
I'm able to reproduce the first two behaviors and i have a hunch on where this code is being called. hooray for custom text editors!

**Comment by dsoskey** [comment]
I've got a fix shipping now that should do the trick: https://github.com/dsoskey/cogwork-librarian/commit/f4bdb64a5d1413297ebc7aa0b6c8ebfb7b9ebe39. Once I verify the fix in production, I'll close this out. feel free to reopen if you still experience this bug.
