### ISSUE TITLE
date format based on set codes

### ISSUE THREAD

**Issue by RojjaCebolla** [dsoskey/cogwork-librarian#9]
One thing scryfall can do is like, `date<mh3 date>=woe`, does coglib have such an option, maybe with slightly different syntax?

**Comment by dsoskey** [comment]
This has shipped. To enable this feature, refresh your card database on https://coglib.sosk.watch/card

**Comment by RojjaCebolla** [comment]
thank you!
also, the url you posted here results in
![image](https://github.com/dsoskey/cogwork-librarian/assets/62170514/662e26dd-0e31-4b4a-8d0d-a8220ae688a6)

**Comment by dsoskey** [comment]
whoops, i thought i had migrated that route too, link fixed
